name       : python-lsp-jsonrpc
version    : 1.0.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/python-lsp-jsonrpc/python-lsp-jsonrpc-1.0.0.tar.gz : 7bec170733db628d3506ea3a5288ff76aa33c70215ed223abdb0d95e957660bd
homepage   : https://github.com/python-lsp/python-lsp-jsonrpc
license    : MIT
component  : programming.python
summary    : JSON RPC 2.0 server library
description: |
    Fork of the python-jsonrpc-server project, maintained by the Spyder IDE team and the community. This is a python 3.6+ server implementation of the JSON RPC 2.0 protocol. This library has been pulled out of the Python LSP Server project.
builddeps  :
    - python-pytest-cov
    - python-ujson
rundeps    :
    - python-ujson
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
